Issue96 update
metno/discovery-metadata-catalog-ingestor pull request #101
Opened 2022-09-16 09:48 UTC by johtoblan

**Summary**: Fixes a bug in the update function caused by UUID handling

TODO: Fix Namespace handling 

**Related issue**: 

**Suggested reviewer(s)**:

**Reviewer checklist**:

* [ ] The headers of all files contain a reference to the repository license
* [ ] 100% test coverage of new code - meaning:
  * [ ] The overall test coverage increased or remained the same as before
  * [ ] Every function is accompanied with a test suite
  * [ ] Tests are both positive (testing that the function work as intended with valid data) and negative (testing that the function behaves as expected with invalid data, e.g., that correct exceptions are thrown)
  * [ ] Functions with optional arguments have separate tests for all options
* [ ] Examples are supported by doctests
* [ ] All tests are passing
* [ ] All names (e.g., files, classes, functions, variables) are explicit
* [ ] Documentation (as docstrings) is complete and understandable

The checklist is based on the S-ENDA conventions and definition of done (see [General Conventions](https://s-enda-documentation.readthedocs.io/en/latest/general_conventions.html)). The above points are not necessarily relevant to all contributions. In that case, please add a short explanation to help the reviewer.

2022-09-16 10:15 UTC, johtoblan commented
Need to discuss namespace handling with @mortenwh

2022-09-26 12:35 UTC, johtoblan commented
Need to handle search in CSW (For update and delete) with Namespace:UUID.

2022-09-27 08:01 UTC, johtoblan commented on dmci/api/app.py
> +        if len(elements) < 2:
Need to accept no-namespace

2022-09-27 08:10 UTC, johtoblan commented on tests/test_api/test_app.py
> +    out = App._check_namespace_UUID("blabla")
Should accept no namespace in delete.

2022-09-27 12:26 UTC, johtoblan commented
PropertyIsIn is not implemented it seems, so we create namespace+:+UUID from incoming request, since we can only do exact matches with PropertyEqualsTo

2022-09-27 14:41 UTC, mortenwh commented
See my comment in #96 - `PropertyIsEqualTo` should be used as before. Old registrations should be updated.

2022-09-28 07:06 UTC, johtoblan commented
> See my comment in #96 - `PropertyIsEqualTo` should be used as before. Old registrations should be updated.

Yes. This is now implemented, with namespace-handling

2022-09-28 10:53 UTC, mortenwh approved these changes
looks good with minor edits

2022-09-28 10:59 UTC, johtoblan commented on tests/test_api/test_app.py
> +    assert client.post("/v1/delete/7278888a96a54ee5845a2051bb8994c8").status_code == 200
Ja

2022-09-28 11:01 UTC, mortenwh commented on tests/test_api/test_app.py
> +    assert client.post("/v1/delete/7278888a96a54ee5845a2051bb8994c8").status_code == 200
supert - kan du registrere den issue'n?

2022-09-28 11:21 UTC, johtoblan commented on dmci/distributors/pycsw_dist.py
> +        if self._worker._namespace != "":
See newest commit

2022-09-28 11:22 UTC, johtoblan commented on dmci/distributors/pycsw_dist.py
> +        if self._worker._namespace != "":
and second newest. forgot to push the doc-string

2022-09-28 11:53 UTC, mortenwh commented on dmci/api/app.py
> +                                metadata_id=metadata_uuid, namespace=namespace)
```suggestion
                                uuid=md_uuid, namespace=md_namespace)
```

2022-09-28 12:04 UTC, mortenwh requested changes
sorry - nå gikk jeg litt mye i detalj her, men med disse endringene blir det litt lettere å forstå hva som skjer...

2022-09-28 12:04 UTC, mortenwh commented on dmci/api/app.py
> +                return None, "", "Malformed metadata id. Should be <namespace>:<UUID>."
```suggestion
                err = "Malformed metadata id. Should be <namespace>:<UUID>."
```

2022-09-28 12:04 UTC, mortenwh commented on dmci/api/app.py
> +            return None, "", f"Failed to convert to UUID: {elements[-1]}"
```suggestion
            err = f"Failed to convert to UUID: {elements[-1]}"
        
        return md_uuid, md_namespace, err
```

2022-09-28 12:04 UTC, mortenwh commented on dmci/api/app.py
> +            return None, "", f"Failed to convert to UUID: {elements[-1]}"
hvorfor `f"Failed to .."`?

2022-09-28 12:07 UTC, mortenwh commented on dmci/api/app.py
> +            return None, "", f"Failed to convert to UUID: {elements[-1]}"
og unngå repetisjon...

2022-09-29 07:48 UTC, mortenwh approved these changes
Looks good!

2022-09-29 07:54 UTC, merged